include $(TOPDIR)/rules.mk

PKG_NAME:=luci-proto-vxlan
PKG_VERSION:=1.0
PKG_RELEASE:=13

PKG_MAINTAINER:=fbinerd <fbinerd@github.com>
PKG_LICENSE:=GPL-3.0

LUCI_TITLE:=Support for VXLAN Protocol
LUCI_DEPENDS:=+vxlan

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
