/*
 * mr80x-appsbl-patcher - apply the embedded appsbl-dualkey.patch to the
 * live 0:APPSBL MTD partition on a Mercusys MR80X v2/v5.
 *
 * The patch (generated by appsbl/scripts/gen-appsbl-dualkey-patch.py from
 * that project's out/appsbl.bin and out/appsbl-dual-key.bin) has two
 * parts, both checked against a full in-RAM copy of the partition before
 * a single byte is ever written to flash:
 *
 *   - a bsdiff-style structural patch (three streams - ctrl/diff/extra,
 *     each raw-DEFLATE compressed and decoded here with puff.c, Mark
 *     Adler's public-domain reference inflate implementation) that
 *     reconstructs the fallback-verification code and everything its
 *     insertion shifted, verified by exact SHA-256 both before and after
 *     applying it. bsdiff's approximate matching recognizes that almost
 *     all of the shifted back half of the image is the SAME bytes just
 *     relocated, so this is a ~20x smaller representation than an earlier
 *     per-region copy list (see gen-appsbl-dualkey-patch.py's docstring)
 *   - two named public-key fields (offset, fixed slot length, expected
 *     RSA bit size baked into patch_data.h) whose VALUE is read at
 *     runtime from /etc/appsbl-dualkey/<name>.b64 - editable by hand
 *     (terminal) or through the LuCI page, not just by rebuilding this
 *     package. Validated structurally (decodes to a well-formed
 *     PUBLICKEYBLOB of the right size and exponent, and is exactly the
 *     slot's fixed length) rather than by a hash, so any correctly
 *     sized, well-formed key is accepted and a wrong-size one is
 *     rejected outright instead of corrupting the layout
 *
 * Three flash-writing modes, all sharing the same erase/write/readback
 * commit_to_flash() helper and never writing anything until every check
 * has already passed against a full in-RAM reconstruction:
 *
 *   - default (apply): 1. read "old" from flash, 2. hash-check against
 *     the patch's pre_sha256, 3. bspatch "old" -> "mid" and hash-check
 *     against mid_sha256, 4. apply the two key fields into "mid", 5.
 *     commit "mid"
 *   - --restore-factory: the reverse of the above. 1. read the live
 *     partition, 2. neutralize its key slots back to the embedded
 *     _stock[] bytes (the actual factory bytes at those offsets) to get
 *     a "mid" candidate, 3. hash-check it against mid_sha256 - this is
 *     what proves the device is actually in the state our own patch
 *     would have produced, not some unrelated or corrupted content, 4.
 *     bspatch "mid" -> "stock" with the embedded reverse streams, 5.
 *     hash-check the result against pre_sha256 - proves the reconstructed
 *     factory image is exact before it's ever written, 6. commit it
 *   - --write-appsbl <file>: no structural checks at all, by design -
 *     this is a raw "flash exactly this file" escape hatch (e.g. for a
 *     dump captured some other way). Only the size is checked (must be
 *     exactly PARTITION_SIZE). Whatever is in the file is what gets
 *     written; the operator is trusting the file, not this tool
 *
 * Deliberately not automatic: this is invoked by hand from a shell
 * (see files/usr/sbin/appsbl-patch-dualkey, which also checks
 * board_name and rootfs_type before ever calling this). Never wired
 * into any boot-time or upgrade-time hook.
 */

#include <errno.h>
#include <fcntl.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <unistd.h>

#include <mtd/mtd-user.h>

#include "base64.h"
#include "puff.h"
#include "sha256.h"
#include "patch_data.h"

#define PARTITION_SIZE 1310720UL /* 0:APPSBL: 0xa blocks * 0x20000, see qcom-mibib.c MR80X_PART_COUNT table */
#define PUBLICKEYBLOB_HEADER_SIZE 20UL /* bType,bVersion,reserved(2),alg_id(4),"RSA1"(4),bits(4),exponent(4) */
#define PUBLICKEYBLOB_EXPONENT 65537UL
#define KEY_DIR "/etc/appsbl-dualkey"
#define KEY_VALUE_MAX 512

/* One decompressed bsdiff patch (ctrl/diff/extra streams). Used for both
 * the forward (stock -> mid) and reverse (mid -> stock) directions. */
struct three_streams {
	unsigned char *ctrl;
	unsigned long ctrl_len;
	unsigned char *diff;
	unsigned long diff_len;
	unsigned char *extra;
	unsigned long extra_len;
};

struct patch {
	unsigned char pre_sha256[32];
	unsigned char mid_sha256[32];
	uint32_t newsize;
	struct three_streams fwd;
};

struct key_field {
	const char *name;
	unsigned int offset;
	unsigned int slotlen;
	unsigned int bits;
	const unsigned char *stock; /* factory bytes at this slot, from patch_data.h - for --restore-factory */
	char b64[KEY_VALUE_MAX]; /* loaded at runtime from KEY_DIR/<name>.b64 */
};

static struct key_field key_fields[] = {
	{
		appsbl_dualkey_pubkey_firmware_rsa2048_name,
		appsbl_dualkey_pubkey_firmware_rsa2048_offset,
		appsbl_dualkey_pubkey_firmware_rsa2048_slotlen,
		appsbl_dualkey_pubkey_firmware_rsa2048_bits,
		appsbl_dualkey_pubkey_firmware_rsa2048_stock,
		{0},
	},
	{
		appsbl_dualkey_pubkey_legacy_rsa1024_name,
		appsbl_dualkey_pubkey_legacy_rsa1024_offset,
		appsbl_dualkey_pubkey_legacy_rsa1024_slotlen,
		appsbl_dualkey_pubkey_legacy_rsa1024_bits,
		appsbl_dualkey_pubkey_legacy_rsa1024_stock,
		{0},
	},
};
#define NUM_KEY_FIELDS (sizeof(key_fields) / sizeof(key_fields[0]))

static void hex32(const unsigned char *h, char out[65])
{
	static const char *digits = "0123456789abcdef";
	int i;

	for (i = 0; i < 32; i++) {
		out[2 * i] = digits[h[i] >> 4];
		out[2 * i + 1] = digits[h[i] & 0xf];
	}
	out[64] = '\0';
}

static void sha256_of(const unsigned char *data, unsigned long len, unsigned char out[32])
{
	SHA256_CTX ctx;

	sha256_init(&ctx);
	sha256_update(&ctx, data, len);
	sha256_final(&ctx, out);
}

/* bsdiff's signed-64-bit control integer encoding: 8 bytes, little-endian
 * magnitude, with the top bit of the last byte as the sign - NOT two's
 * complement. Mirrors gen-appsbl-dualkey-patch.py's offtin() exactly;
 * verified byte-for-byte against real bsdiff/bspatch output before this
 * format was ever committed. */
static int64_t offtin(const unsigned char *b)
{
	uint64_t y = b[7] & 0x7f;
	int i;

	for (i = 6; i >= 0; i--)
		y = y * 256 + b[i];
	return (b[7] & 0x80) ? -(int64_t)y : (int64_t)y;
}

/* Decompresses one raw-DEFLATE stream (comp_len bytes at comp) into a
 * freshly malloc'd buffer of exactly raw_len bytes, via puff.c. Returns
 * NULL on any failure (malformed deflate data, or a decompressed size
 * that doesn't match what the patch header promised). */
static unsigned char *inflate_stream(const unsigned char *comp, unsigned long comp_len, unsigned long raw_len)
{
	unsigned char *out;
	unsigned long destlen = raw_len;
	unsigned long sourcelen = comp_len;
	int ret;

	out = malloc(raw_len ? raw_len : 1);
	if (!out) {
		fprintf(stderr, "appsbl-patch: out of memory\n");
		return NULL;
	}

	ret = puff(out, &destlen, comp, &sourcelen);
	if (ret != 0 || destlen != raw_len) {
		fprintf(stderr, "appsbl-patch: embedded patch stream failed to decompress (puff ret=%d)\n", ret);
		free(out);
		return NULL;
	}

	return out;
}

/* Parses the (raw_len, comp_len, comp_bytes) x3 [ctrl, diff, extra]
 * section shared by both appsbl_dualkey_patch[] and
 * appsbl_dualkey_restore[], decompressing each via inflate_stream(). */
static int parse_three_streams(const unsigned char *d, unsigned long len, unsigned long *off, struct three_streams *s)
{
	int i;

	memset(s, 0, sizeof(*s));

	for (i = 0; i < 3; i++) {
		uint32_t raw_len, comp_len;
		unsigned char **dst;
		unsigned long *dst_len;

		if (*off + 8 > len) {
			fprintf(stderr, "appsbl-patch: truncated patch data\n");
			return -1;
		}
		raw_len = (uint32_t)d[*off] | ((uint32_t)d[*off + 1] << 8) |
			  ((uint32_t)d[*off + 2] << 16) | ((uint32_t)d[*off + 3] << 24);
		comp_len = (uint32_t)d[*off + 4] | ((uint32_t)d[*off + 5] << 8) |
			   ((uint32_t)d[*off + 6] << 16) | ((uint32_t)d[*off + 7] << 24);
		*off += 8;
		if (*off + comp_len > len) {
			fprintf(stderr, "appsbl-patch: truncated patch stream %d\n", i);
			return -1;
		}

		switch (i) {
		case 0:
			dst = &s->ctrl;
			dst_len = &s->ctrl_len;
			break;
		case 1:
			dst = &s->diff;
			dst_len = &s->diff_len;
			break;
		default:
			dst = &s->extra;
			dst_len = &s->extra_len;
			break;
		}

		*dst = inflate_stream(d + *off, comp_len, raw_len);
		if (!*dst)
			return -1;
		*dst_len = raw_len;
		*off += comp_len;
	}

	return 0;
}

static void free_three_streams(struct three_streams *s)
{
	free(s->ctrl);
	free(s->diff);
	free(s->extra);
}

/* d/len here is appsbl_dualkey_patch[] from patch_data.h - machine-generated
 * bsdiff diff data, not something to hand-tweak (see that header's own
 * comment for why). This function only reads the format; regenerate the
 * header via gen-appsbl-dualkey-patch.py to actually change the patch. */
static int parse_patch(struct patch *p)
{
	const unsigned char *d = appsbl_dualkey_patch;
	unsigned long len = appsbl_dualkey_patch_len;
	unsigned long off;

	memset(p, 0, sizeof(*p));

	if (len < 11 + 32 + 32 + 4 || memcmp(d, "MR80XPATCH", 10) || d[10] != 4) {
		fprintf(stderr, "appsbl-patch: embedded patch data is malformed or wrong version\n");
		return -1;
	}
	off = 11;
	memcpy(p->pre_sha256, d + off, 32);
	off += 32;
	memcpy(p->mid_sha256, d + off, 32);
	off += 32;
	p->newsize = (uint32_t)d[off] | ((uint32_t)d[off + 1] << 8) |
		     ((uint32_t)d[off + 2] << 16) | ((uint32_t)d[off + 3] << 24);
	off += 4;

	if (p->newsize != PARTITION_SIZE) {
		fprintf(stderr, "appsbl-patch: embedded patch targets %u bytes, expected %lu\n",
			p->newsize, PARTITION_SIZE);
		return -1;
	}

	return parse_three_streams(d, len, &off, &p->fwd);
}

static void free_patch(struct patch *p)
{
	free_three_streams(&p->fwd);
}

/* appsbl_dualkey_restore[] - the reverse bsdiff (mid -> stock), used only
 * by --restore-factory. No hashes of its own: parse_patch() already
 * carries pre_sha256/mid_sha256, which is what this direction is checked
 * against (see the mode block in main()). */
static int parse_restore_patch(struct three_streams *rev)
{
	const unsigned char *d = appsbl_dualkey_restore;
	unsigned long len = appsbl_dualkey_restore_len;
	unsigned long off;
	uint32_t newsize;

	memset(rev, 0, sizeof(*rev));

	if (len < 11 + 4 || memcmp(d, "MR80XRESTR", 10) || d[10] != 1) {
		fprintf(stderr, "appsbl-patch: embedded restore data is malformed or wrong version\n");
		return -1;
	}
	off = 11;
	newsize = (uint32_t)d[off] | ((uint32_t)d[off + 1] << 8) |
		  ((uint32_t)d[off + 2] << 16) | ((uint32_t)d[off + 3] << 24);
	off += 4;
	if (newsize != PARTITION_SIZE) {
		fprintf(stderr, "appsbl-patch: embedded restore data targets %u bytes, expected %lu\n",
			newsize, PARTITION_SIZE);
		return -1;
	}

	return parse_three_streams(d, len, &off, rev);
}

/* bspatch's control-flow: walks the ctrl stream in (match_len, extra_len,
 * seek_len) triples. For each matched span, new[i] = old[i] + diff[i]
 * (byte-wise addition mod 256, NOT XOR - verified against real bsdiff/
 * bspatch output). Then extra_len bytes are copied verbatim from the
 * extra stream. Then oldpos is adjusted by seek_len, which can be
 * negative. Bounds-checked throughout even though the streams are
 * compiled-in data, not attacker input - a corrupted build should fail
 * loudly here rather than overrun a heap buffer. Used both forward
 * (stock -> mid) and reverse (mid -> stock, for --restore-factory). */
static int apply_bspatch(const struct three_streams *s, const unsigned char *old, unsigned long oldsize,
			  unsigned char *out, unsigned long newsize)
{
	unsigned long newpos = 0, oldpos = 0, cpos = 0, dpos = 0, epos = 0;

	while (newpos < newsize) {
		int64_t match_len, copy_len, seek_len;
		unsigned long i;

		if (cpos + 24 > s->ctrl_len) {
			fprintf(stderr, "appsbl-patch: bspatch ctrl stream truncated\n");
			return -1;
		}
		match_len = offtin(s->ctrl + cpos);
		cpos += 8;
		copy_len = offtin(s->ctrl + cpos);
		cpos += 8;
		seek_len = offtin(s->ctrl + cpos);
		cpos += 8;

		if (match_len < 0 || (unsigned long)match_len > newsize - newpos ||
		    (unsigned long)match_len > oldsize - oldpos ||
		    (unsigned long)match_len > s->diff_len - dpos) {
			fprintf(stderr, "appsbl-patch: bspatch control record out of bounds\n");
			return -1;
		}
		for (i = 0; i < (unsigned long)match_len; i++)
			out[newpos + i] = (unsigned char)(old[oldpos + i] + s->diff[dpos + i]);
		newpos += (unsigned long)match_len;
		oldpos += (unsigned long)match_len;
		dpos += (unsigned long)match_len;

		if (copy_len < 0 || (unsigned long)copy_len > newsize - newpos ||
		    (unsigned long)copy_len > s->extra_len - epos) {
			fprintf(stderr, "appsbl-patch: bspatch control record out of bounds\n");
			return -1;
		}
		memcpy(out + newpos, s->extra + epos, (size_t)copy_len);
		newpos += (unsigned long)copy_len;
		epos += (unsigned long)copy_len;

		if (seek_len >= 0) {
			if ((unsigned long)seek_len > oldsize - oldpos) {
				fprintf(stderr, "appsbl-patch: bspatch seek out of bounds\n");
				return -1;
			}
			oldpos += (unsigned long)seek_len;
		} else {
			if ((unsigned long)(-seek_len) > oldpos) {
				fprintf(stderr, "appsbl-patch: bspatch seek out of bounds\n");
				return -1;
			}
			oldpos -= (unsigned long)(-seek_len);
		}
	}

	return 0;
}

/* Loads field->b64 from KEY_DIR/<name>.b64, trimming trailing whitespace
 * (a plain text editor saving the file almost always adds a trailing
 * newline; the slot-length check in validate_key_field() would reject
 * an otherwise-correct key over a stray \n if this didn't strip it). */
static int load_key_field(struct key_field *field)
{
	char path[256];
	FILE *f;
	size_t n;

	snprintf(path, sizeof(path), "%s/%s.b64", KEY_DIR, field->name);
	f = fopen(path, "r");
	if (!f) {
		fprintf(stderr, "appsbl-patch: cannot open %s: %s\n", path, strerror(errno));
		return -1;
	}
	n = fread(field->b64, 1, sizeof(field->b64) - 1, f);
	fclose(f);
	field->b64[n] = '\0';

	while (n > 0 && (field->b64[n - 1] == '\n' || field->b64[n - 1] == '\r' ||
			 field->b64[n - 1] == ' ' || field->b64[n - 1] == '\t'))
		field->b64[--n] = '\0';

	return 0;
}

/* Validates that field->b64 decodes to a well-formed PUBLICKEYBLOB of
 * exactly field->bits, with the standard exponent - and that its text
 * length is exactly the slot it will be written into. Does not check
 * it against any specific expected key: any structurally valid,
 * correctly-sized key is accepted, which is what makes rotating the
 * key a matter of editing this string rather than regenerating the
 * whole patch. */
static int validate_key_field(const struct key_field *field)
{
	unsigned char raw[512];
	long rawlen;
	unsigned long expected_rawlen;
	uint32_t bits, exponent;

	if (strlen(field->b64) != field->slotlen) {
		fprintf(stderr,
			"appsbl-patch: %s key is %zu base64 chars, expected exactly %u - "
			"only a same-bit-size key fits this slot\n",
			field->name, strlen(field->b64), field->slotlen);
		return -1;
	}

	rawlen = base64_decode(field->b64, raw, sizeof(raw));
	if (rawlen < 0) {
		fprintf(stderr, "appsbl-patch: %s key is not valid base64\n", field->name);
		return -1;
	}

	expected_rawlen = PUBLICKEYBLOB_HEADER_SIZE + field->bits / 8;
	if ((unsigned long)rawlen != expected_rawlen) {
		fprintf(stderr, "appsbl-patch: %s key decodes to %ld bytes, expected %lu\n",
			field->name, rawlen, expected_rawlen);
		return -1;
	}

	if (raw[0] != 0x06 || raw[1] != 0x02 || memcmp(raw + 8, "RSA1", 4)) {
		fprintf(stderr, "appsbl-patch: %s key has an invalid PUBLICKEYBLOB header\n", field->name);
		return -1;
	}

	bits = (uint32_t)raw[12] | ((uint32_t)raw[13] << 8) | ((uint32_t)raw[14] << 16) | ((uint32_t)raw[15] << 24);
	if (bits != field->bits) {
		fprintf(stderr, "appsbl-patch: %s key declares %u bits, expected %u\n",
			field->name, bits, field->bits);
		return -1;
	}

	exponent = (uint32_t)raw[16] | ((uint32_t)raw[17] << 8) | ((uint32_t)raw[18] << 16) | ((uint32_t)raw[19] << 24);
	if (exponent != PUBLICKEYBLOB_EXPONENT) {
		fprintf(stderr, "appsbl-patch: %s key has exponent %u, expected %lu\n",
			field->name, exponent, PUBLICKEYBLOB_EXPONENT);
		return -1;
	}

	return 0;
}

static struct key_field *find_key_field(const char *name)
{
	unsigned int k;

	for (k = 0; k < NUM_KEY_FIELDS; k++)
		if (!strcmp(key_fields[k].name, name))
			return &key_fields[k];
	return NULL;
}

/* Validates value against field's slot length and PUBLICKEYBLOB structure
 * (same rules as validate_key_field(), just against a candidate value
 * rather than whatever is already on disk) and, only if it passes,
 * atomically replaces KEY_DIR/<name>.b64 with it. Never leaves a partial
 * write behind: written to a temp file first, then renamed into place. */
static int set_key_field(const char *name, const char *value)
{
	struct key_field *field = find_key_field(name);
	struct key_field candidate;
	char path[256];
	char tmp_path[272];
	FILE *f;
	int fd;

	if (!field) {
		fprintf(stderr, "appsbl-patch: no such key field '%s'\n", name);
		return -1;
	}

	candidate = *field;
	if (strlen(value) >= sizeof(candidate.b64)) {
		fprintf(stderr, "appsbl-patch: %s value is implausibly long, refusing\n", name);
		return -1;
	}
	strcpy(candidate.b64, value);

	if (validate_key_field(&candidate))
		return -1; /* validate_key_field already explained why */

	snprintf(path, sizeof(path), "%s/%s.b64", KEY_DIR, name);
	snprintf(tmp_path, sizeof(tmp_path), "%s.tmp", path);

	fd = open(tmp_path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
	if (fd < 0) {
		fprintf(stderr, "appsbl-patch: cannot create %s: %s\n", tmp_path, strerror(errno));
		return -1;
	}
	f = fdopen(fd, "w");
	if (!f) {
		close(fd);
		fprintf(stderr, "appsbl-patch: fdopen failed: %s\n", strerror(errno));
		return -1;
	}
	fprintf(f, "%s\n", value);
	if (fclose(f) || rename(tmp_path, path)) {
		fprintf(stderr, "appsbl-patch: failed writing %s: %s\n", path, strerror(errno));
		unlink(tmp_path);
		return -1;
	}

	printf("appsbl-patch: %s key (%u-bit) validated and saved to %s\n", name, field->bits, path);
	return 0;
}

static int read_full(int fd, unsigned char *buf, size_t len)
{
	size_t got = 0;

	while (got < len) {
		ssize_t n = read(fd, buf + got, len - got);

		if (n < 0) {
			if (errno == EINTR)
				continue;
			return -1;
		}
		if (n == 0)
			break;
		got += (size_t)n;
	}
	return got == len ? 0 : -1;
}

static int write_full(int fd, const unsigned char *buf, size_t len)
{
	size_t done = 0;

	while (done < len) {
		ssize_t n = write(fd, buf + done, len - done);

		if (n < 0) {
			if (errno == EINTR)
				continue;
			return -1;
		}
		done += (size_t)n;
	}
	return 0;
}

/* Erases and rewrites the WHOLE partition in one pass (not incremental
 * in-place patching of live flash), reading back and comparing every
 * block as it goes. Shared by all three commit paths (apply,
 * --restore-factory, --write-appsbl) - by the time this is called,
 * `data` has already been fully decided and verified; this function's
 * only job is to get it onto the flash chip correctly. */
static int commit_to_flash(int fd, const mtd_info_t *info, const unsigned char *data)
{
	unsigned char *verify;
	unsigned long block;
	int ret = -1;

	verify = malloc(info->erasesize);
	if (!verify) {
		fprintf(stderr, "appsbl-patch: out of memory\n");
		return -1;
	}

	for (block = 0; block * info->erasesize < PARTITION_SIZE; block++) {
		unsigned long offset = block * info->erasesize;
		int64_t bad_addr = (int64_t)offset;
		struct erase_info_user erase;

		if (ioctl(fd, MEMGETBADBLOCK, &bad_addr) > 0) {
			fprintf(stderr, "appsbl-patch: block at 0x%lx is marked bad - aborting\n", offset);
			goto out;
		}

		erase.start = offset;
		erase.length = info->erasesize;
		if (ioctl(fd, MEMERASE, &erase)) {
			fprintf(stderr, "appsbl-patch: erase at 0x%lx failed: %s\n", offset, strerror(errno));
			goto out;
		}
		if (lseek(fd, (off_t)offset, SEEK_SET) != (off_t)offset ||
		    write_full(fd, data + offset, info->erasesize)) {
			fprintf(stderr, "appsbl-patch: write at 0x%lx failed: %s\n", offset, strerror(errno));
			goto out;
		}
		if (lseek(fd, (off_t)offset, SEEK_SET) != (off_t)offset ||
		    read_full(fd, verify, info->erasesize) ||
		    memcmp(verify, data + offset, info->erasesize)) {
			fprintf(stderr, "appsbl-patch: readback verification failed at 0x%lx\n", offset);
			goto out;
		}
		printf("appsbl-patch: block at 0x%lx written and verified\n", offset);
	}

	if (fsync(fd) && errno != EINVAL && errno != ENOTSUP) {
		fprintf(stderr, "appsbl-patch: fsync failed: %s\n", strerror(errno));
		goto out;
	}

	ret = 0;
out:
	free(verify);
	return ret;
}

static void print_usage(const char *argv0)
{
	fprintf(stderr, "usage: %s <mtd-device> [--yes-really]\n", argv0);
	fprintf(stderr, "       %s <mtd-device> --restore-factory [--yes-really]\n", argv0);
	fprintf(stderr, "       %s <mtd-device> --write-appsbl <file> [--yes-really]\n", argv0);
	fprintf(stderr, "       %s --show-keys\n", argv0);
	fprintf(stderr, "       %s --set-key <name> <base64-value>\n", argv0);
}

enum patch_mode {
	MODE_APPLY,
	MODE_RESTORE_FACTORY,
	MODE_WRITE_APPSBL,
};

int main(int argc, char **argv)
{
	struct patch p;
	struct three_streams rev = {0};
	unsigned char *old = NULL;
	unsigned char *mid = NULL;
	unsigned char hash[32];
	char hexbuf[65];
	mtd_info_t info;
	int fd = -1;
	enum patch_mode mode = MODE_APPLY;
	const char *write_file = NULL;
	bool commit = false;
	int ret = EXIT_FAILURE;
	unsigned int k;
	bool patch_parsed = false;
	bool rev_parsed = false;
	int i;

	if (argc == 2 && strcmp(argv[1], "--show-keys") == 0) {
		int all_ok = 1;

		for (k = 0; k < NUM_KEY_FIELDS; k++) {
			struct key_field *field = &key_fields[k];
			int ok;

			printf("%s (%u-bit), from %s/%s.b64:\n", field->name, field->bits, KEY_DIR, field->name);
			if (load_key_field(field)) {
				all_ok = 0;
				continue;
			}
			printf("  %s\n", field->b64);
			ok = !validate_key_field(field);
			printf("  %s\n", ok ? "valid" : "INVALID - will be rejected, see above");
			all_ok = all_ok && ok;
		}
		return all_ok ? EXIT_SUCCESS : EXIT_FAILURE;
	}

	if (argc == 4 && strcmp(argv[1], "--set-key") == 0)
		return set_key_field(argv[2], argv[3]) ? EXIT_FAILURE : EXIT_SUCCESS;

	if (argc < 2) {
		print_usage(argv[0]);
		return EXIT_FAILURE;
	}

	for (i = 2; i < argc; i++) {
		if (!strcmp(argv[i], "--yes-really")) {
			commit = true;
		} else if (!strcmp(argv[i], "--restore-factory")) {
			mode = MODE_RESTORE_FACTORY;
		} else if (!strcmp(argv[i], "--write-appsbl")) {
			mode = MODE_WRITE_APPSBL;
			if (i + 1 >= argc) {
				print_usage(argv[0]);
				return EXIT_FAILURE;
			}
			write_file = argv[++i];
		} else {
			print_usage(argv[0]);
			return EXIT_FAILURE;
		}
	}

	if (mode == MODE_APPLY || mode == MODE_RESTORE_FACTORY) {
		if (parse_patch(&p))
			return EXIT_FAILURE;
		patch_parsed = true;
	}

	if (mode == MODE_APPLY) {
		for (k = 0; k < NUM_KEY_FIELDS; k++)
			if (load_key_field(&key_fields[k]) || validate_key_field(&key_fields[k]))
				goto out;
	}

	if (mode == MODE_RESTORE_FACTORY) {
		if (parse_restore_patch(&rev))
			goto out;
		rev_parsed = true;
	}

	/* Probing never writes, so it never needs the partition's write flag -
	 * 0:appsbl is `read-only;` in the DTS, and the kernel refuses O_RDWR opens
	 * on that regardless of what the caller intends to do with it. Only the
	 * --yes-really path needs O_RDWR, and needs the caller (see
	 * files/usr/sbin/appsbl-patch-dualkey) to have already loaded
	 * kmod-mtd-rw to lift that flag first. */
	fd = open(argv[1], commit ? O_RDWR : O_RDONLY);
	if (fd < 0) {
		fprintf(stderr, "appsbl-patch: cannot open %s: %s\n", argv[1], strerror(errno));
		goto out;
	}

	if (ioctl(fd, MEMGETINFO, &info)) {
		fprintf(stderr, "appsbl-patch: MEMGETINFO failed on %s: %s\n", argv[1], strerror(errno));
		goto out;
	}
	if (info.size != PARTITION_SIZE) {
		fprintf(stderr,
			"appsbl-patch: %s is %u bytes, expected exactly %lu (0:APPSBL) - refusing\n",
			argv[1], info.size, PARTITION_SIZE);
		goto out;
	}

	if (mode == MODE_WRITE_APPSBL) {
		FILE *f;
		long fsize;

		f = fopen(write_file, "rb");
		if (!f) {
			fprintf(stderr, "appsbl-patch: cannot open %s: %s\n", write_file, strerror(errno));
			goto out;
		}
		if (fseek(f, 0, SEEK_END) || (fsize = ftell(f)) < 0 || fseek(f, 0, SEEK_SET)) {
			fprintf(stderr, "appsbl-patch: cannot determine size of %s\n", write_file);
			fclose(f);
			goto out;
		}
		if ((unsigned long)fsize != PARTITION_SIZE) {
			fprintf(stderr,
				"appsbl-patch: %s is %ld bytes, expected exactly %lu (0:APPSBL) - refusing\n",
				write_file, fsize, PARTITION_SIZE);
			fclose(f);
			goto out;
		}

		mid = malloc(PARTITION_SIZE);
		if (!mid) {
			fprintf(stderr, "appsbl-patch: out of memory\n");
			fclose(f);
			goto out;
		}
		if (fread(mid, 1, PARTITION_SIZE, f) != PARTITION_SIZE) {
			fprintf(stderr, "appsbl-patch: failed reading %s: %s\n", write_file, strerror(errno));
			fclose(f);
			goto out;
		}
		fclose(f);

		printf("appsbl-patch: %s is exactly %lu bytes - no structural checks are done in this "
		       "mode, whatever is in the file is what would be written\n", write_file, PARTITION_SIZE);

		if (!commit) {
			printf("appsbl-patch: probe successful; no data was written (pass --yes-really to write)\n");
			ret = EXIT_SUCCESS;
			goto out;
		}

		if (commit_to_flash(fd, &info, mid))
			goto out;

		printf("appsbl-patch: %s fully rewritten and verified from %s\n", argv[1], write_file);
		ret = EXIT_SUCCESS;
		goto out;
	}

	old = malloc(PARTITION_SIZE);
	mid = malloc(PARTITION_SIZE);
	if (!old || !mid) {
		fprintf(stderr, "appsbl-patch: out of memory\n");
		goto out;
	}
	if (read_full(fd, old, PARTITION_SIZE)) {
		fprintf(stderr, "appsbl-patch: failed reading %s: %s\n", argv[1], strerror(errno));
		goto out;
	}

	if (mode == MODE_APPLY) {
		sha256_of(old, PARTITION_SIZE, hash);
		if (memcmp(hash, p.pre_sha256, 32)) {
			hex32(hash, hexbuf);
			fprintf(stderr,
				"appsbl-patch: current %s does not match this patch's expected input\n"
				"  got:      %s\n", argv[1], hexbuf);
			hex32(p.pre_sha256, hexbuf);
			fprintf(stderr, "  expected: %s\n"
				"refusing - this is not the stock APPSBL this patch was built for\n",
				hexbuf);
			goto out;
		}
		printf("appsbl-patch: current %s matches the expected stock image\n", argv[1]);

		if (apply_bspatch(&p.fwd, old, PARTITION_SIZE, mid, PARTITION_SIZE)) {
			fprintf(stderr, "appsbl-patch: failed to reconstruct the structural patch\n");
			goto out;
		}

		sha256_of(mid, PARTITION_SIZE, hash);
		if (memcmp(hash, p.mid_sha256, 32)) {
			hex32(hash, hexbuf);
			fprintf(stderr,
				"appsbl-patch: structurally patched result does not match expectations\n"
				"  got:      %s\n", hexbuf);
			hex32(p.mid_sha256, hexbuf);
			fprintf(stderr, "  expected: %s\n"
				"refusing to write anything to flash\n", hexbuf);
			goto out;
		}
		printf("appsbl-patch: structural patch matches expectations\n");

		for (k = 0; k < NUM_KEY_FIELDS; k++) {
			const struct key_field *field = &key_fields[k];

			memcpy(mid + field->offset, field->b64, field->slotlen);
			printf("appsbl-patch: %s key (%u-bit) applied and structurally validated\n",
			       field->name, field->bits);
		}
	} else { /* MODE_RESTORE_FACTORY */
		/* Neutralize the live key slots back to their factory bytes, so the
		 * result is directly comparable to mid_sha256 regardless of whatever
		 * key values are currently applied. */
		memcpy(mid, old, PARTITION_SIZE);
		for (k = 0; k < NUM_KEY_FIELDS; k++) {
			const struct key_field *field = &key_fields[k];

			memcpy(mid + field->offset, field->stock, field->slotlen);
		}

		sha256_of(mid, PARTITION_SIZE, hash);
		if (memcmp(hash, p.mid_sha256, 32)) {
			hex32(hash, hexbuf);
			fprintf(stderr,
				"appsbl-patch: current %s (with key fields neutralized) does not match "
				"the state our own patch would have produced\n"
				"  got:      %s\n", argv[1], hexbuf);
			hex32(p.mid_sha256, hexbuf);
			fprintf(stderr, "  expected: %s\n"
				"refusing - this does not look like our own dual-key patch, not restoring over it\n",
				hexbuf);
			goto out;
		}
		printf("appsbl-patch: current %s (key fields neutralized) matches our own patched state\n", argv[1]);

		/* Reuse `old` as the reconstructed-factory-image buffer - its
		 * current contents (the live, patched partition) are no longer
		 * needed past this point. */
		if (apply_bspatch(&rev, mid, PARTITION_SIZE, old, PARTITION_SIZE)) {
			fprintf(stderr, "appsbl-patch: failed to reconstruct the factory image\n");
			goto out;
		}

		sha256_of(old, PARTITION_SIZE, hash);
		if (memcmp(hash, p.pre_sha256, 32)) {
			hex32(hash, hexbuf);
			fprintf(stderr,
				"appsbl-patch: reconstructed factory image does not match the expected hash\n"
				"  got:      %s\n", hexbuf);
			hex32(p.pre_sha256, hexbuf);
			fprintf(stderr, "  expected: %s\n"
				"refusing to write anything to flash\n", hexbuf);
			goto out;
		}
		printf("appsbl-patch: reconstructed factory image matches the expected factory hash (pre_sha256)\n");

		/* From here on, `old` holds the verified factory image - write that. */
		memcpy(mid, old, PARTITION_SIZE);
	}

	if (!commit) {
		printf("appsbl-patch: probe successful; no data was written (pass --yes-really to write)\n");
		ret = EXIT_SUCCESS;
		goto out;
	}

	if (commit_to_flash(fd, &info, mid))
		goto out;

	if (mode == MODE_RESTORE_FACTORY) {
		sha256_of(mid, PARTITION_SIZE, hash);
		if (memcmp(hash, p.pre_sha256, 32)) {
			/* commit_to_flash() already read back and compared every
			 * block, so this can only fail if `mid` itself was wrong -
			 * already ruled out above. Kept as a final belt-and-braces
			 * confirmation that what's now on flash really does hash to
			 * the known factory image. */
			fprintf(stderr, "appsbl-patch: post-write hash check failed unexpectedly\n");
			goto out;
		}
		printf("appsbl-patch: restore verified against the expected factory hash (pre_sha256)\n");
	}

	printf("appsbl-patch: %s fully rewritten and verified\n", argv[1]);
	ret = EXIT_SUCCESS;
out:
	free(mid);
	free(old);
	if (rev_parsed)
		free_three_streams(&rev);
	if (patch_parsed)
		free_patch(&p);
	if (fd >= 0)
		close(fd);
	return ret;
}
