/* Auto-generated by appsbl/scripts/extract-vendor-keys.py. DO NOT HAND-EDIT.
 *
 * TP-Link/Mercusys's REAL public firmware-signing keys (l_rsaPubKey /
 * l_rsa2048PubKey), extracted directly from a stock (non-dual-key)
 * out/appsbl.bin - NOT this project's own research keys (those live under
 * keys/public (*.publickeyblob.b64) and patch_data.h's _stock[] arrays,
 * which are a completely different pair - see this script's docstring).
 * Used only to verify the signature on an uploaded official Mercusys
 * firmware image (appsbl-verify-image.c) before trusting it for anything.
 */
static const char appsbl_vendor_pubkey_rsa1024[] = "BgIAAACkAABSU0ExAAQAAAEAAQD9lxDCQ5DFNSYJBriTmTmZlEMYVgGcZTO+AIwmdVjhaeJI6wWtN7DqCaHQlOqJ2xvKNrLB+wA1NxUh7VDViymotq/+9QDf7qEtJHmesjirvPN6Hfrf+FO4/hmjbVXgytHORxGta5KW4QHVIwyMSVPOvMC4A5lFIh+D1kJW5GXWtA==";
static const unsigned int appsbl_vendor_pubkey_rsa1024_bits = 1024U;
static const char appsbl_vendor_pubkey_rsa2048[] = "BgIAAAwkAABSU0ExAAgAAAEAAQCdocMdSvAkLmNelNXLolhx4/OqVrxm6g1XCIlMdTgWAAbA4GkSZbU4juBCWdUgc7oYCinkzpjttbZpFY1FS1GfYAiga2S9czL3tB2+7YMcwozwXW504nXGEJ5ShmvvZy6iu/N54hFauwram8Sbc7ax1sJ1rRA78jWz7i1mX/AeIPgWw336DQeYhAyZlFjVGkyFK1miLDgDeMmejJVZu3v3iu6VyuyVSGngRP+RyROzjvefY45kBM3h+2HM9oF3BkeUvS6TMasCmgMQEepVOLLcgbPlogmpxxlFRxTm0sjyIIhMj422ClU06ze31E+TBwtFiagwfw85f+gqzsOIo8e2";
static const unsigned int appsbl_vendor_pubkey_rsa2048_bits = 2048U;
